# Generated by Django 4.2 on 2023-04-26 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='use date')),
                ('status', models.CharField(choices=[('C', 'Clean'), ('D', 'Dirty')], default='C', max_length=1)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cup')),
            ],
        ),
    ]
