# Generated by Django 4.2 on 2023-04-27 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_content_cup_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='content',
            name='temp',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
